const Colors = {
  light: {
    primary: '#ef8022',
    accent: '#fce21b',
    background: 'white',
    background_2: '#F5F7FB',
    surface: 'white',
    error: '#B00020',
    warning: 'orange',
    success: 'green',
    love: 'red',
    text: 'black',
    onBackground: '#000000',
    onSurface: '#000000',
    disabled: 'rgba(0,0,0,0.26)',
    placeholder: 'rgba(0,0,0,0.54)',
    backdrop: 'rgba(0,0,0,0.5)',
    notification: '#6200ee',
    sub_text: 'rgba(0,0,0,0.54)',
    text_placeholder: '#B3B2B3',
    sun: '#FDD835',
    moon: 'rgba(0,0,0,0.8)',
    borderColorGrey: '#c1c5ca',
    superGrey: '#ecedef',
    greyBold: '#535353',
    greyLight: '#9ea6ac',
    greyThin: '#c1c1c1',
  },
  dark: {
    primary: 'rgb(82,102,222)',
    // accent: '#03dac4',
    accent: '#fce21b',
    background: 'rgb(40,42,54)',
    background_2: 'rgb(40,42,54)',
    surface: 'white',
    error: '#B00020',
    warning: 'orange',
    success: 'green',
    love: 'red',
    text: 'white',
    onBackground: '#000',
    onSurface: 'black',
    disabled: 'rgba(0,0,0,0.26)',
    placeholder: 'white',
    backdrop: 'white',
    notification: '#6200ee',
    sub_text: 'white',
    text_placeholder: 'white',
    sun: '#FFEB3B',
    moon: '#FFF',
    sub_background: 'rgb(152,97,186)',
    appintro_next: '#89F3DC',
    borderColorGrey: '#c1c5ca',
    superGrey: '#ecedef',
    greyBold: 'white',
    greyLight: '#9ea6ac',
    greyThin: '#c1c1c1',
  },
};

export {Colors};
