const PLACES = [
  {
    id: '01',
    value: 'Thành phố Hà Nội',
    children: [
      {id: '001', value: 'Quận Ba Đình'},
      {id: '002', value: 'Quận Hoàn Kiếm'},
      {id: '003', value: 'Quận Tây Hồ'},
      {id: '004', value: 'Quận Long Biên'},
      {id: '005', value: 'Quận Cầu Giấy'},
      {id: '006', value: 'Quận Đống Đa'},
      {id: '007', value: 'Quận Hai Bà Trưng'},
      {id: '008', value: 'Quận Hoàng Mai'},
      {id: '009', value: 'Quận Thanh Xuân'},
      {id: '016', value: 'Huyện Sóc Sơn'},
      {id: '017', value: 'Huyện Đông Anh'},
      {id: '018', value: 'Huyện Gia Lâm'},
      {id: '019', value: 'Quận Nam Từ Liêm'},
      {id: '020', value: 'Huyện Thanh Trì'},
      {id: '021', value: 'Quận Bắc Từ Liêm'},
      {id: '250', value: 'Huyện Mê Linh'},
      {id: '268', value: 'Quận Hà Đông'},
      {id: '269', value: 'Thị xã Sơn Tây'},
      {id: '271', value: 'Huyện Ba Vì'},
      {id: '272', value: 'Huyện Phúc Thọ'},
      {id: '273', value: 'Huyện Đan Phượng'},
      {id: '274', value: 'Huyện Hoài Đức'},
      {id: '275', value: 'Huyện Quốc Oai'},
      {id: '276', value: 'Huyện Thạch Thất'},
      {id: '277', value: 'Huyện Chương Mỹ'},
      {id: '278', value: 'Huyện Thanh Oai'},
      {id: '279', value: 'Huyện Thường Tín'},
      {id: '280', value: 'Huyện Phú Xuyên'},
      {id: '281', value: 'Huyện Ứng Hòa'},
      {id: '282', value: 'Huyện Mỹ Đức'},
    ],
  },
  {
    id: '02',
    value: 'Tỉnh Hà Giang',
    children: [
      {id: '024', value: 'Thành phố Hà Giang'},
      {id: '026', value: 'Huyện Đồng Văn'},
      {id: '027', value: 'Huyện Mèo Vạc'},
      {id: '028', value: 'Huyện Yên Minh'},
      {id: '029', value: 'Huyện Quản Bạ'},
      {id: '030', value: 'Huyện Vị Xuyên'},
      {id: '031', value: 'Huyện Bắc Mê'},
      {id: '032', value: 'Huyện Hoàng Su Phì'},
      {id: '033', value: 'Huyện Xín Mần'},
      {id: '034', value: 'Huyện Bắc Quang'},
      {id: '035', value: 'Huyện Quang Bình'},
    ],
  },
  {
    id: '04',
    value: 'Tỉnh Cao Bằng',
    children: [
      {id: '040', value: 'Thành phố Cao Bằng'},
      {id: '042', value: 'Huyện Bảo Lâm'},
      {id: '043', value: 'Huyện Bảo Lạc'},
      {id: '045', value: 'Huyện Hà Quảng'},
      {id: '047', value: 'Huyện Trùng Khánh'},
      {id: '048', value: 'Huyện Hạ Lang'},
      {id: '049', value: 'Huyện Quảng Hòa'},
      {id: '051', value: 'Huyện Hoà An'},
      {id: '052', value: 'Huyện Nguyên Bình'},
      {id: '053', value: 'Huyện Thạch An'},
    ],
  },
  {
    id: '06',
    value: 'Tỉnh Bắc Kạn',
    children: [
      {id: '058', value: 'Thành Phố Bắc Kạn'},
      {id: '060', value: 'Huyện Pác Nặm'},
      {id: '061', value: 'Huyện Ba Bể'},
      {id: '062', value: 'Huyện Ngân Sơn'},
      {id: '063', value: 'Huyện Bạch Thông'},
      {id: '064', value: 'Huyện Chợ Đồn'},
      {id: '065', value: 'Huyện Chợ Mới'},
      {id: '066', value: 'Huyện Na Rì'},
    ],
  },
  {
    id: '08',
    value: 'Tỉnh Tuyên Quang',
    children: [
      {id: '070', value: 'Thành phố Tuyên Quang'},
      {id: '071', value: 'Huyện Lâm Bình'},
      {id: '072', value: 'Huyện Na Hang'},
      {id: '073', value: 'Huyện Chiêm Hóa'},
      {id: '074', value: 'Huyện Hàm Yên'},
      {id: '075', value: 'Huyện Yên Sơn'},
      {id: '076', value: 'Huyện Sơn Dương'},
    ],
  },
  {
    id: '10',
    value: 'Tỉnh Lào Cai',
    children: [
      {id: '080', value: 'Thành phố Lào Cai'},
      {id: '082', value: 'Huyện Bát Xát'},
      {id: '083', value: 'Huyện Mường Khương'},
      {id: '084', value: 'Huyện Si Ma Cai'},
      {id: '085', value: 'Huyện Bắc Hà'},
      {id: '086', value: 'Huyện Bảo Thắng'},
      {id: '087', value: 'Huyện Bảo Yên'},
      {id: '088', value: 'Thị xã Sa Pa'},
      {id: '089', value: 'Huyện Văn Bàn'},
    ],
  },
  {
    id: '11',
    value: 'Tỉnh Điện Biên',
    children: [
      {id: '094', value: 'Thành phố Điện Biên Phủ'},
      {id: '095', value: 'Thị Xã Mường Lay'},
      {id: '096', value: 'Huyện Mường Nhé'},
      {id: '097', value: 'Huyện Mường Chà'},
      {id: '098', value: 'Huyện Tủa Chùa'},
      {id: '099', value: 'Huyện Tuần Giáo'},
      {id: '100', value: 'Huyện Điện Biên'},
      {id: '101', value: 'Huyện Điện Biên Đông'},
      {id: '102', value: 'Huyện Mường Ảng'},
      {id: '103', value: 'Huyện Nậm Pồ'},
    ],
  },
  {
    id: '12',
    value: 'Tỉnh Lai Châu',
    children: [
      {id: '105', value: 'Thành phố Lai Châu'},
      {id: '106', value: 'Huyện Tam Đường'},
      {id: '107', value: 'Huyện Mường Tè'},
      {id: '108', value: 'Huyện Sìn Hồ'},
      {id: '109', value: 'Huyện Phong Thổ'},
      {id: '110', value: 'Huyện Than Uyên'},
      {id: '111', value: 'Huyện Tân Uyên'},
      {id: '112', value: 'Huyện Nậm Nhùn'},
    ],
  },
  {
    id: '14',
    value: 'Tỉnh Sơn La',
    children: [
      {id: '116', value: 'Thành phố Sơn La'},
      {id: '118', value: 'Huyện Quỳnh Nhai'},
      {id: '119', value: 'Huyện Thuận Châu'},
      {id: '120', value: 'Huyện Mường La'},
      {id: '121', value: 'Huyện Bắc Yên'},
      {id: '122', value: 'Huyện Phù Yên'},
      {id: '123', value: 'Huyện Mộc Châu'},
      {id: '124', value: 'Huyện Yên Châu'},
      {id: '125', value: 'Huyện Mai Sơn'},
      {id: '126', value: 'Huyện Sông Mã'},
      {id: '127', value: 'Huyện Sốp Cộp'},
      {id: '128', value: 'Huyện Vân Hồ'},
    ],
  },
  {
    id: '15',
    value: 'Tỉnh Yên Bái',
    children: [
      {id: '132', value: 'Thành phố Yên Bái'},
      {id: '133', value: 'Thị xã Nghĩa Lộ'},
      {id: '135', value: 'Huyện Lục Yên'},
      {id: '136', value: 'Huyện Văn Yên'},
      {id: '137', value: 'Huyện Mù Căng Chải'},
      {id: '138', value: 'Huyện Trấn Yên'},
      {id: '139', value: 'Huyện Trạm Tấu'},
      {id: '140', value: 'Huyện Văn Chấn'},
      {id: '141', value: 'Huyện Yên Bình'},
    ],
  },
  {
    id: '17',
    value: 'Tỉnh Hoà Bình',
    children: [
      {id: '148', value: 'Thành phố Hòa Bình'},
      {id: '150', value: 'Huyện Đà Bắc'},
      {id: '152', value: 'Huyện Lương Sơn'},
      {id: '153', value: 'Huyện Kim Bôi'},
      {id: '154', value: 'Huyện Cao Phong'},
      {id: '155', value: 'Huyện Tân Lạc'},
      {id: '156', value: 'Huyện Mai Châu'},
      {id: '157', value: 'Huyện Lạc Sơn'},
      {id: '158', value: 'Huyện Yên Thủy'},
      {id: '159', value: 'Huyện Lạc Thủy'},
    ],
  },
  {
    id: '19',
    value: 'Tỉnh Thái Nguyên',
    children: [
      {id: '164', value: 'Thành phố Thái Nguyên'},
      {id: '165', value: 'Thành phố Sông Công'},
      {id: '167', value: 'Huyện Định Hóa'},
      {id: '168', value: 'Huyện Phú Lương'},
      {id: '169', value: 'Huyện Đồng Hỷ'},
      {id: '170', value: 'Huyện Võ Nhai'},
      {id: '171', value: 'Huyện Đại Từ'},
      {id: '172', value: 'Thị xã Phổ Yên'},
      {id: '173', value: 'Huyện Phú Bình'},
    ],
  },
  {
    id: '20',
    value: 'Tỉnh Lạng Sơn',
    children: [
      {id: '178', value: 'Thành phố Lạng Sơn'},
      {id: '180', value: 'Huyện Tràng Định'},
      {id: '181', value: 'Huyện Bình Gia'},
      {id: '182', value: 'Huyện Văn Lãng'},
      {id: '183', value: 'Huyện Cao Lộc'},
      {id: '184', value: 'Huyện Văn Quan'},
      {id: '185', value: 'Huyện Bắc Sơn'},
      {id: '186', value: 'Huyện Hữu Lũng'},
      {id: '187', value: 'Huyện Chi Lăng'},
      {id: '188', value: 'Huyện Lộc Bình'},
      {id: '189', value: 'Huyện Đình Lập'},
    ],
  },
  {
    id: '22',
    value: 'Tỉnh Quảng Ninh',
    children: [
      {id: '193', value: 'Thành phố Hạ Long'},
      {id: '194', value: 'Thành phố Móng Cái'},
      {id: '195', value: 'Thành phố Cẩm Phả'},
      {id: '196', value: 'Thành phố Uông Bí'},
      {id: '198', value: 'Huyện Bình Liêu'},
      {id: '199', value: 'Huyện Tiên Yên'},
      {id: '200', value: 'Huyện Đầm Hà'},
      {id: '201', value: 'Huyện Hải Hà'},
      {id: '202', value: 'Huyện Ba Chẽ'},
      {id: '203', value: 'Huyện Vân Đồn'},
      {id: '205', value: 'Thị xã Đông Triều'},
      {id: '206', value: 'Thị xã Quảng Yên'},
      {id: '207', value: 'Huyện Cô Tô'},
    ],
  },
  {
    id: '24',
    value: 'Tỉnh Bắc Giang',
    children: [
      {id: '213', value: 'Thành phố Bắc Giang'},
      {id: '215', value: 'Huyện Yên Thế'},
      {id: '216', value: 'Huyện Tân Yên'},
      {id: '217', value: 'Huyện Lạng Giang'},
      {id: '218', value: 'Huyện Lục Nam'},
      {id: '219', value: 'Huyện Lục Ngạn'},
      {id: '220', value: 'Huyện Sơn Động'},
      {id: '221', value: 'Huyện Yên Dũng'},
      {id: '222', value: 'Huyện Việt Yên'},
      {id: '223', value: 'Huyện Hiệp Hòa'},
    ],
  },
  {
    id: '25',
    value: 'Tỉnh Phú Thọ',
    children: [
      {id: '227', value: 'Thành phố Việt Trì'},
      {id: '228', value: 'Thị xã Phú Thọ'},
      {id: '230', value: 'Huyện Đoan Hùng'},
      {id: '231', value: 'Huyện Hạ Hoà'},
      {id: '232', value: 'Huyện Thanh Ba'},
      {id: '233', value: 'Huyện Phù Ninh'},
      {id: '234', value: 'Huyện Yên Lập'},
      {id: '235', value: 'Huyện Cẩm Khê'},
      {id: '236', value: 'Huyện Tam Nông'},
      {id: '237', value: 'Huyện Lâm Thao'},
      {id: '238', value: 'Huyện Thanh Sơn'},
      {id: '239', value: 'Huyện Thanh Thuỷ'},
      {id: '240', value: 'Huyện Tân Sơn'},
    ],
  },
  {
    id: '26',
    value: 'Tỉnh Vĩnh Phúc',
    children: [
      {id: '243', value: 'Thành phố Vĩnh Yên'},
      {id: '244', value: 'Thành phố Phúc Yên'},
      {id: '246', value: 'Huyện Lập Thạch'},
      {id: '247', value: 'Huyện Tam Dương'},
      {id: '248', value: 'Huyện Tam Đảo'},
      {id: '249', value: 'Huyện Bình Xuyên'},
      {id: '251', value: 'Huyện Yên Lạc'},
      {id: '252', value: 'Huyện Vĩnh Tường'},
      {id: '253', value: 'Huyện Sông Lô'},
    ],
  },
  {
    id: '27',
    value: 'Tỉnh Bắc Ninh',
    children: [
      {id: '256', value: 'Thành phố Bắc Ninh'},
      {id: '258', value: 'Huyện Yên Phong'},
      {id: '259', value: 'Huyện Quế Võ'},
      {id: '260', value: 'Huyện Tiên Du'},
      {id: '261', value: 'Thành phố Từ Sơn'},
      {id: '262', value: 'Huyện Thuận Thành'},
      {id: '263', value: 'Huyện Gia Bình'},
      {id: '264', value: 'Huyện Lương Tài'},
    ],
  },
  {
    id: '30',
    value: 'Tỉnh Hải Dương',
    children: [
      {id: '288', value: 'Thành phố Hải Dương'},
      {id: '290', value: 'Thành phố Chí Linh'},
      {id: '291', value: 'Huyện Nam Sách'},
      {id: '292', value: 'Thị xã Kinh Môn'},
      {id: '293', value: 'Huyện Kim Thành'},
      {id: '294', value: 'Huyện Thanh Hà'},
      {id: '295', value: 'Huyện Cẩm Giàng'},
      {id: '296', value: 'Huyện Bình Giang'},
      {id: '297', value: 'Huyện Gia Lộc'},
      {id: '298', value: 'Huyện Tứ Kỳ'},
      {id: '299', value: 'Huyện Ninh Giang'},
      {id: '300', value: 'Huyện Thanh Miện'},
    ],
  },
  {
    id: '31',
    value: 'Thành phố Hải Phòng',
    children: [
      {id: '303', value: 'Quận Hồng Bàng'},
      {id: '304', value: 'Quận Ngô Quyền'},
      {id: '305', value: 'Quận Lê Chân'},
      {id: '306', value: 'Quận Hải An'},
      {id: '307', value: 'Quận Kiến An'},
      {id: '308', value: 'Quận Đồ Sơn'},
      {id: '309', value: 'Quận Dương Kinh'},
      {id: '311', value: 'Huyện Thuỷ Nguyên'},
      {id: '312', value: 'Huyện An Dương'},
      {id: '313', value: 'Huyện An Lão'},
      {id: '314', value: 'Huyện Kiến Thuỵ'},
      {id: '315', value: 'Huyện Tiên Lãng'},
      {id: '316', value: 'Huyện Vĩnh Bảo'},
      {id: '317', value: 'Huyện Cát Hải'},
      {id: '318', value: 'Huyện Bạch Long Vĩ'},
    ],
  },
  {
    id: '33',
    value: 'Tỉnh Hưng Yên',
    children: [
      {id: '323', value: 'Thành phố Hưng Yên'},
      {id: '325', value: 'Huyện Văn Lâm'},
      {id: '326', value: 'Huyện Văn Giang'},
      {id: '327', value: 'Huyện Yên Mỹ'},
      {id: '328', value: 'Thị xã Mỹ Hào'},
      {id: '329', value: 'Huyện Ân Thi'},
      {id: '330', value: 'Huyện Khoái Châu'},
      {id: '331', value: 'Huyện Kim Động'},
      {id: '332', value: 'Huyện Tiên Lữ'},
      {id: '333', value: 'Huyện Phù Cừ'},
    ],
  },
  {
    id: '34',
    value: 'Tỉnh Thái Bình',
    children: [
      {id: '336', value: 'Thành phố Thái Bình'},
      {id: '338', value: 'Huyện Quỳnh Phụ'},
      {id: '339', value: 'Huyện Hưng Hà'},
      {id: '340', value: 'Huyện Đông Hưng'},
      {id: '341', value: 'Huyện Thái Thụy'},
      {id: '342', value: 'Huyện Tiền Hải'},
      {id: '343', value: 'Huyện Kiến Xương'},
      {id: '344', value: 'Huyện Vũ Thư'},
    ],
  },
  {
    id: '35',
    value: 'Tỉnh Hà Nam',
    children: [
      {id: '347', value: 'Thành phố Phủ Lý'},
      {id: '349', value: 'Thị xã Duy Tiên'},
      {id: '350', value: 'Huyện Kim Bảng'},
      {id: '351', value: 'Huyện Thanh Liêm'},
      {id: '352', value: 'Huyện Bình Lục'},
      {id: '353', value: 'Huyện Lý Nhân'},
    ],
  },
  {
    id: '36',
    value: 'Tỉnh Nam Định',
    children: [
      {id: '356', value: 'Thành phố Nam Định'},
      {id: '358', value: 'Huyện Mỹ Lộc'},
      {id: '359', value: 'Huyện Vụ Bản'},
      {id: '360', value: 'Huyện Ý Yên'},
      {id: '361', value: 'Huyện Nghĩa Hưng'},
      {id: '362', value: 'Huyện Nam Trực'},
      {id: '363', value: 'Huyện Trực Ninh'},
      {id: '364', value: 'Huyện Xuân Trường'},
      {id: '365', value: 'Huyện Giao Thủy'},
      {id: '366', value: 'Huyện Hải Hậu'},
    ],
  },
  {
    id: '37',
    value: 'Tỉnh Ninh Bình',
    children: [
      {id: '369', value: 'Thành phố Ninh Bình'},
      {id: '370', value: 'Thành phố Tam Điệp'},
      {id: '372', value: 'Huyện Nho Quan'},
      {id: '373', value: 'Huyện Gia Viễn'},
      {id: '374', value: 'Huyện Hoa Lư'},
      {id: '375', value: 'Huyện Yên Khánh'},
      {id: '376', value: 'Huyện Kim Sơn'},
      {id: '377', value: 'Huyện Yên Mô'},
    ],
  },
  {
    id: '38',
    value: 'Tỉnh Thanh Hóa',
    children: [
      {id: '380', value: 'Thành phố Thanh Hóa'},
      {id: '381', value: 'Thị xã Bỉm Sơn'},
      {id: '382', value: 'Thành phố Sầm Sơn'},
      {id: '384', value: 'Huyện Mường Lát'},
      {id: '385', value: 'Huyện Quan Hóa'},
      {id: '386', value: 'Huyện Bá Thước'},
      {id: '387', value: 'Huyện Quan Sơn'},
      {id: '388', value: 'Huyện Lang Chánh'},
      {id: '389', value: 'Huyện Ngọc Lặc'},
      {id: '390', value: 'Huyện Cẩm Thủy'},
      {id: '391', value: 'Huyện Thạch Thành'},
      {id: '392', value: 'Huyện Hà Trung'},
      {id: '393', value: 'Huyện Vĩnh Lộc'},
      {id: '394', value: 'Huyện Yên Định'},
      {id: '395', value: 'Huyện Thọ Xuân'},
      {id: '396', value: 'Huyện Thường Xuân'},
      {id: '397', value: 'Huyện Triệu Sơn'},
      {id: '398', value: 'Huyện Thiệu Hóa'},
      {id: '399', value: 'Huyện Hoằng Hóa'},
      {id: '400', value: 'Huyện Hậu Lộc'},
      {id: '401', value: 'Huyện Nga Sơn'},
      {id: '402', value: 'Huyện Như Xuân'},
      {id: '403', value: 'Huyện Như Thanh'},
      {id: '404', value: 'Huyện Nông Cống'},
      {id: '405', value: 'Huyện Đông Sơn'},
      {id: '406', value: 'Huyện Quảng Xương'},
      {id: '407', value: 'Thị xã Nghi Sơn'},
    ],
  },
  {
    id: '40',
    value: 'Tỉnh Nghệ An',
    children: [
      {id: '412', value: 'Thành phố Vinh'},
      {id: '413', value: 'Thị xã Cửa Lò'},
      {id: '414', value: 'Thị xã Thái Hoà'},
      {id: '415', value: 'Huyện Quế Phong'},
      {id: '416', value: 'Huyện Quỳ Châu'},
      {id: '417', value: 'Huyện Kỳ Sơn'},
      {id: '418', value: 'Huyện Tương Dương'},
      {id: '419', value: 'Huyện Nghĩa Đàn'},
      {id: '420', value: 'Huyện Quỳ Hợp'},
      {id: '421', value: 'Huyện Quỳnh Lưu'},
      {id: '422', value: 'Huyện Con Cuông'},
      {id: '423', value: 'Huyện Tân Kỳ'},
      {id: '424', value: 'Huyện Anh Sơn'},
      {id: '425', value: 'Huyện Diễn Châu'},
      {id: '426', value: 'Huyện Yên Thành'},
      {id: '427', value: 'Huyện Đô Lương'},
      {id: '428', value: 'Huyện Thanh Chương'},
      {id: '429', value: 'Huyện Nghi Lộc'},
      {id: '430', value: 'Huyện Nam Đàn'},
      {id: '431', value: 'Huyện Hưng Nguyên'},
      {id: '432', value: 'Thị xã Hoàng Mai'},
    ],
  },
  {
    id: '42',
    value: 'Tỉnh Hà Tĩnh',
    children: [
      {id: '436', value: 'Thành phố Hà Tĩnh'},
      {id: '437', value: 'Thị xã Hồng Lĩnh'},
      {id: '439', value: 'Huyện Hương Sơn'},
      {id: '440', value: 'Huyện Đức Thọ'},
      {id: '441', value: 'Huyện Vũ Quang'},
      {id: '442', value: 'Huyện Nghi Xuân'},
      {id: '443', value: 'Huyện Can Lộc'},
      {id: '444', value: 'Huyện Hương Khê'},
      {id: '445', value: 'Huyện Thạch Hà'},
      {id: '446', value: 'Huyện Cẩm Xuyên'},
      {id: '447', value: 'Huyện Kỳ Anh'},
      {id: '448', value: 'Huyện Lộc Hà'},
      {id: '449', value: 'Thị xã Kỳ Anh'},
    ],
  },
  {
    id: '44',
    value: 'Tỉnh Quảng Bình',
    children: [
      {id: '450', value: 'Thành Phố Đồng Hới'},
      {id: '452', value: 'Huyện Minh Hóa'},
      {id: '453', value: 'Huyện Tuyên Hóa'},
      {id: '454', value: 'Huyện Quảng Trạch'},
      {id: '455', value: 'Huyện Bố Trạch'},
      {id: '456', value: 'Huyện Quảng Ninh'},
      {id: '457', value: 'Huyện Lệ Thủy'},
      {id: '458', value: 'Thị xã Ba Đồn'},
    ],
  },
  {
    id: '45',
    value: 'Tỉnh Quảng Trị',
    children: [
      {id: '461', value: 'Thành phố Đông Hà'},
      {id: '462', value: 'Thị xã Quảng Trị'},
      {id: '464', value: 'Huyện Vĩnh Linh'},
      {id: '465', value: 'Huyện Hướng Hóa'},
      {id: '466', value: 'Huyện Gio Linh'},
      {id: '467', value: 'Huyện Đa Krông'},
      {id: '468', value: 'Huyện Cam Lộ'},
      {id: '469', value: 'Huyện Triệu Phong'},
      {id: '470', value: 'Huyện Hải Lăng'},
      {id: '471', value: 'Huyện Cồn Cỏ'},
    ],
  },
  {
    id: '46',
    value: 'Tỉnh Thừa Thiên Huế',
    children: [
      {id: '474', value: 'Thành phố Huế'},
      {id: '476', value: 'Huyện Phong Điền'},
      {id: '477', value: 'Huyện Quảng Điền'},
      {id: '478', value: 'Huyện Phú Vang'},
      {id: '479', value: 'Thị xã Hương Thủy'},
      {id: '480', value: 'Thị xã Hương Trà'},
      {id: '481', value: 'Huyện A Lưới'},
      {id: '482', value: 'Huyện Phú Lộc'},
      {id: '483', value: 'Huyện Nam Đông'},
    ],
  },
  {
    id: '48',
    value: 'Thành phố Đà Nẵng',
    children: [
      {id: '490', value: 'Quận Liên Chiểu'},
      {id: '491', value: 'Quận Thanh Khê'},
      {id: '492', value: 'Quận Hải Châu'},
      {id: '493', value: 'Quận Sơn Trà'},
      {id: '494', value: 'Quận Ngũ Hành Sơn'},
      {id: '495', value: 'Quận Cẩm Lệ'},
      {id: '497', value: 'Huyện Hòa Vang'},
      {id: '498', value: 'Huyện Hoàng Sa'},
    ],
  },
  {
    id: '49',
    value: 'Tỉnh Quảng Nam',
    children: [
      {id: '502', value: 'Thành phố Tam Kỳ'},
      {id: '503', value: 'Thành phố Hội An'},
      {id: '504', value: 'Huyện Tây Giang'},
      {id: '505', value: 'Huyện Đông Giang'},
      {id: '506', value: 'Huyện Đại Lộc'},
      {id: '507', value: 'Thị xã Điện Bàn'},
      {id: '508', value: 'Huyện Duy Xuyên'},
      {id: '509', value: 'Huyện Quế Sơn'},
      {id: '510', value: 'Huyện Nam Giang'},
      {id: '511', value: 'Huyện Phước Sơn'},
      {id: '512', value: 'Huyện Hiệp Đức'},
      {id: '513', value: 'Huyện Thăng Bình'},
      {id: '514', value: 'Huyện Tiên Phước'},
      {id: '515', value: 'Huyện Bắc Trà My'},
      {id: '516', value: 'Huyện Nam Trà My'},
      {id: '517', value: 'Huyện Núi Thành'},
      {id: '518', value: 'Huyện Phú Ninh'},
      {id: '519', value: 'Huyện Nông Sơn'},
    ],
  },
  {
    id: '51',
    value: 'Tỉnh Quảng Ngãi',
    children: [
      {id: '522', value: 'Thành phố Quảng Ngãi'},
      {id: '524', value: 'Huyện Bình Sơn'},
      {id: '525', value: 'Huyện Trà Bồng'},
      {id: '527', value: 'Huyện Sơn Tịnh'},
      {id: '528', value: 'Huyện Tư Nghĩa'},
      {id: '529', value: 'Huyện Sơn Hà'},
      {id: '530', value: 'Huyện Sơn Tây'},
      {id: '531', value: 'Huyện Minh Long'},
      {id: '532', value: 'Huyện Nghĩa Hành'},
      {id: '533', value: 'Huyện Mộ Đức'},
      {id: '534', value: 'Thị xã Đức Phổ'},
      {id: '535', value: 'Huyện Ba Tơ'},
      {id: '536', value: 'Huyện Lý Sơn'},
    ],
  },
  {
    id: '52',
    value: 'Tỉnh Bình Định',
    children: [
      {id: '540', value: 'Thành phố Quy Nhơn'},
      {id: '542', value: 'Huyện An Lão'},
      {id: '543', value: 'Thị xã Hoài Nhơn'},
      {id: '544', value: 'Huyện Hoài Ân'},
      {id: '545', value: 'Huyện Phù Mỹ'},
      {id: '546', value: 'Huyện Vĩnh Thạnh'},
      {id: '547', value: 'Huyện Tây Sơn'},
      {id: '548', value: 'Huyện Phù Cát'},
      {id: '549', value: 'Thị xã An Nhơn'},
      {id: '550', value: 'Huyện Tuy Phước'},
      {id: '551', value: 'Huyện Vân Canh'},
    ],
  },
  {
    id: '54',
    value: 'Tỉnh Phú Yên',
    children: [
      {id: '555', value: 'Thành phố Tuy Hoà'},
      {id: '557', value: 'Thị xã Sông Cầu'},
      {id: '558', value: 'Huyện Đồng Xuân'},
      {id: '559', value: 'Huyện Tuy An'},
      {id: '560', value: 'Huyện Sơn Hòa'},
      {id: '561', value: 'Huyện Sông Hinh'},
      {id: '562', value: 'Huyện Tây Hoà'},
      {id: '563', value: 'Huyện Phú Hoà'},
      {id: '564', value: 'Thị xã Đông Hòa'},
    ],
  },
  {
    id: '56',
    value: 'Tỉnh Khánh Hòa',
    children: [
      {id: '568', value: 'Thành phố Nha Trang'},
      {id: '569', value: 'Thành phố Cam Ranh'},
      {id: '570', value: 'Huyện Cam Lâm'},
      {id: '571', value: 'Huyện Vạn Ninh'},
      {id: '572', value: 'Thị xã Ninh Hòa'},
      {id: '573', value: 'Huyện Khánh Vĩnh'},
      {id: '574', value: 'Huyện Diên Khánh'},
      {id: '575', value: 'Huyện Khánh Sơn'},
      {id: '576', value: 'Huyện Trường Sa'},
    ],
  },
  {
    id: '58',
    value: 'Tỉnh Ninh Thuận',
    children: [
      {id: '582', value: 'Thành phố Phan Rang-Tháp Chàm'},
      {id: '584', value: 'Huyện Bác Ái'},
      {id: '585', value: 'Huyện Ninh Sơn'},
      {id: '586', value: 'Huyện Ninh Hải'},
      {id: '587', value: 'Huyện Ninh Phước'},
      {id: '588', value: 'Huyện Thuận Bắc'},
      {id: '589', value: 'Huyện Thuận Nam'},
    ],
  },
  {
    id: '60',
    value: 'Tỉnh Bình Thuận',
    children: [
      {id: '593', value: 'Thành phố Phan Thiết'},
      {id: '594', value: 'Thị xã La Gi'},
      {id: '595', value: 'Huyện Tuy Phong'},
      {id: '596', value: 'Huyện Bắc Bình'},
      {id: '597', value: 'Huyện Hàm Thuận Bắc'},
      {id: '598', value: 'Huyện Hàm Thuận Nam'},
      {id: '599', value: 'Huyện Tánh Linh'},
      {id: '600', value: 'Huyện Đức Linh'},
      {id: '601', value: 'Huyện Hàm Tân'},
      {id: '602', value: 'Huyện Phú Quí'},
    ],
  },
  {
    id: '62',
    value: 'Tỉnh Kon Tum',
    children: [
      {id: '608', value: 'Thành phố Kon Tum'},
      {id: '610', value: 'Huyện Đắk Glei'},
      {id: '611', value: 'Huyện Ngọc Hồi'},
      {id: '612', value: 'Huyện Đắk Tô'},
      {id: '613', value: 'Huyện Kon Plông'},
      {id: '614', value: 'Huyện Kon Rẫy'},
      {id: '615', value: 'Huyện Đắk Hà'},
      {id: '616', value: 'Huyện Sa Thầy'},
      {id: '617', value: 'Huyện Tu Mơ Rông'},
      {id: '618', value: "Huyện Ia H' Drai"},
    ],
  },
  {
    id: '64',
    value: 'Tỉnh Gia Lai',
    children: [
      {id: '622', value: 'Thành phố Pleiku'},
      {id: '623', value: 'Thị xã An Khê'},
      {id: '624', value: 'Thị xã Ayun Pa'},
      {id: '625', value: 'Huyện KBang'},
      {id: '626', value: 'Huyện Đăk Đoa'},
      {id: '627', value: 'Huyện Chư Păh'},
      {id: '628', value: 'Huyện Ia Grai'},
      {id: '629', value: 'Huyện Mang Yang'},
      {id: '630', value: 'Huyện Kông Chro'},
      {id: '631', value: 'Huyện Đức Cơ'},
      {id: '632', value: 'Huyện Chư Prông'},
      {id: '633', value: 'Huyện Chư Sê'},
      {id: '634', value: 'Huyện Đăk Pơ'},
      {id: '635', value: 'Huyện Ia Pa'},
      {id: '637', value: 'Huyện Krông Pa'},
      {id: '638', value: 'Huyện Phú Thiện'},
      {id: '639', value: 'Huyện Chư Pưh'},
    ],
  },
  {
    id: '66',
    value: 'Tỉnh Đắk Lắk',
    children: [
      {id: '643', value: 'Thành phố Buôn Ma Thuột'},
      {id: '644', value: 'Thị Xã Buôn Hồ'},
      {id: '645', value: "Huyện Ea H'leo"},
      {id: '646', value: 'Huyện Ea Súp'},
      {id: '647', value: 'Huyện Buôn Đôn'},
      {id: '648', value: "Huyện Cư M'gar"},
      {id: '649', value: 'Huyện Krông Búk'},
      {id: '650', value: 'Huyện Krông Năng'},
      {id: '651', value: 'Huyện Ea Kar'},
      {id: '652', value: "Huyện M'Đrắk"},
      {id: '653', value: 'Huyện Krông Bông'},
      {id: '654', value: 'Huyện Krông Pắc'},
      {id: '655', value: 'Huyện Krông A Na'},
      {id: '656', value: 'Huyện Lắk'},
      {id: '657', value: 'Huyện Cư Kuin'},
    ],
  },
  {
    id: '67',
    value: 'Tỉnh Đắk Nông',
    children: [
      {id: '660', value: 'Thành phố Gia Nghĩa'},
      {id: '661', value: 'Huyện Đăk Glong'},
      {id: '662', value: 'Huyện Cư Jút'},
      {id: '663', value: 'Huyện Đắk Mil'},
      {id: '664', value: 'Huyện Krông Nô'},
      {id: '665', value: 'Huyện Đắk Song'},
      {id: '666', value: "Huyện Đắk R'Lấp"},
      {id: '667', value: 'Huyện Tuy Đức'},
    ],
  },
  {
    id: '68',
    value: 'Tỉnh Lâm Đồng',
    children: [
      {id: '672', value: 'Thành phố Đà Lạt'},
      {id: '673', value: 'Thành phố Bảo Lộc'},
      {id: '674', value: 'Huyện Đam Rông'},
      {id: '675', value: 'Huyện Lạc Dương'},
      {id: '676', value: 'Huyện Lâm Hà'},
      {id: '677', value: 'Huyện Đơn Dương'},
      {id: '678', value: 'Huyện Đức Trọng'},
      {id: '679', value: 'Huyện Di Linh'},
      {id: '680', value: 'Huyện Bảo Lâm'},
      {id: '681', value: 'Huyện Đạ Huoai'},
      {id: '682', value: 'Huyện Đạ Tẻh'},
      {id: '683', value: 'Huyện Cát Tiên'},
    ],
  },
  {
    id: '70',
    value: 'Tỉnh Bình Phước',
    children: [
      {id: '688', value: 'Thị xã Phước Long'},
      {id: '689', value: 'Thành phố Đồng Xoài'},
      {id: '690', value: 'Thị xã Bình Long'},
      {id: '691', value: 'Huyện Bù Gia Mập'},
      {id: '692', value: 'Huyện Lộc Ninh'},
      {id: '693', value: 'Huyện Bù Đốp'},
      {id: '694', value: 'Huyện Hớn Quản'},
      {id: '695', value: 'Huyện Đồng Phú'},
      {id: '696', value: 'Huyện Bù Đăng'},
      {id: '697', value: 'Huyện Chơn Thành'},
      {id: '698', value: 'Huyện Phú Riềng'},
    ],
  },
  {
    id: '72',
    value: 'Tỉnh Tây Ninh',
    children: [
      {id: '703', value: 'Thành phố Tây Ninh'},
      {id: '705', value: 'Huyện Tân Biên'},
      {id: '706', value: 'Huyện Tân Châu'},
      {id: '707', value: 'Huyện Dương Minh Châu'},
      {id: '708', value: 'Huyện Châu Thành'},
      {id: '709', value: 'Thị xã Hòa Thành'},
      {id: '710', value: 'Huyện Gò Dầu'},
      {id: '711', value: 'Huyện Bến Cầu'},
      {id: '712', value: 'Thị xã Trảng Bàng'},
    ],
  },
  {
    id: '74',
    value: 'Tỉnh Bình Dương',
    children: [
      {id: '718', value: 'Thành phố Thủ Dầu Một'},
      {id: '719', value: 'Huyện Bàu Bàng'},
      {id: '720', value: 'Huyện Dầu Tiếng'},
      {id: '721', value: 'Thị xã Bến Cát'},
      {id: '722', value: 'Huyện Phú Giáo'},
      {id: '723', value: 'Thị xã Tân Uyên'},
      {id: '724', value: 'Thành phố Dĩ An'},
      {id: '725', value: 'Thành phố Thuận An'},
      {id: '726', value: 'Huyện Bắc Tân Uyên'},
    ],
  },
  {
    id: '75',
    value: 'Tỉnh Đồng Nai',
    children: [
      {id: '731', value: 'Thành phố Biên Hòa'},
      {id: '732', value: 'Thành phố Long Khánh'},
      {id: '734', value: 'Huyện Tân Phú'},
      {id: '735', value: 'Huyện Vĩnh Cửu'},
      {id: '736', value: 'Huyện Định Quán'},
      {id: '737', value: 'Huyện Trảng Bom'},
      {id: '738', value: 'Huyện Thống Nhất'},
      {id: '739', value: 'Huyện Cẩm Mỹ'},
      {id: '740', value: 'Huyện Long Thành'},
      {id: '741', value: 'Huyện Xuân Lộc'},
      {id: '742', value: 'Huyện Nhơn Trạch'},
    ],
  },
  {
    id: '77',
    value: 'Tỉnh Bà Rịa - Vũng Tàu',
    children: [
      {id: '747', value: 'Thành phố Vũng Tàu'},
      {id: '748', value: 'Thành phố Bà Rịa'},
      {id: '750', value: 'Huyện Châu Đức'},
      {id: '751', value: 'Huyện Xuyên Mộc'},
      {id: '752', value: 'Huyện Long Điền'},
      {id: '753', value: 'Huyện Đất Đỏ'},
      {id: '754', value: 'Thị xã Phú Mỹ'},
      {id: '755', value: 'Huyện Côn Đảo'},
    ],
  },
  {
    id: '79',
    value: 'Thành phố Hồ Chí Minh',
    children: [
      {id: '760', value: 'Quận 1'},
      {id: '761', value: 'Quận 12'},
      {id: '764', value: 'Quận Gò Vấp'},
      {id: '765', value: 'Quận Bình Thạnh'},
      {id: '766', value: 'Quận Tân Bình'},
      {id: '767', value: 'Quận Tân Phú'},
      {id: '768', value: 'Quận Phú Nhuận'},
      {id: '769', value: 'Thành phố Thủ Đức'},
      {id: '770', value: 'Quận 3'},
      {id: '771', value: 'Quận 10'},
      {id: '772', value: 'Quận 11'},
      {id: '773', value: 'Quận 4'},
      {id: '774', value: 'Quận 5'},
      {id: '775', value: 'Quận 6'},
      {id: '776', value: 'Quận 8'},
      {id: '777', value: 'Quận Bình Tân'},
      {id: '778', value: 'Quận 7'},
      {id: '783', value: 'Huyện Củ Chi'},
      {id: '784', value: 'Huyện Hóc Môn'},
      {id: '785', value: 'Huyện Bình Chánh'},
      {id: '786', value: 'Huyện Nhà Bè'},
      {id: '787', value: 'Huyện Cần Giờ'},
    ],
  },
  {
    id: '80',
    value: 'Tỉnh Long An',
    children: [
      {id: '794', value: 'Thành phố Tân An'},
      {id: '795', value: 'Thị xã Kiến Tường'},
      {id: '796', value: 'Huyện Tân Hưng'},
      {id: '797', value: 'Huyện Vĩnh Hưng'},
      {id: '798', value: 'Huyện Mộc Hóa'},
      {id: '799', value: 'Huyện Tân Thạnh'},
      {id: '800', value: 'Huyện Thạnh Hóa'},
      {id: '801', value: 'Huyện Đức Huệ'},
      {id: '802', value: 'Huyện Đức Hòa'},
      {id: '803', value: 'Huyện Bến Lức'},
      {id: '804', value: 'Huyện Thủ Thừa'},
      {id: '805', value: 'Huyện Tân Trụ'},
      {id: '806', value: 'Huyện Cần Đước'},
      {id: '807', value: 'Huyện Cần Giuộc'},
      {id: '808', value: 'Huyện Châu Thành'},
    ],
  },
  {
    id: '82',
    value: 'Tỉnh Tiền Giang',
    children: [
      {id: '815', value: 'Thành phố Mỹ Tho'},
      {id: '816', value: 'Thị xã Gò Công'},
      {id: '817', value: 'Thị xã Cai Lậy'},
      {id: '818', value: 'Huyện Tân Phước'},
      {id: '819', value: 'Huyện Cái Bè'},
      {id: '820', value: 'Huyện Cai Lậy'},
      {id: '821', value: 'Huyện Châu Thành'},
      {id: '822', value: 'Huyện Chợ Gạo'},
      {id: '823', value: 'Huyện Gò Công Tây'},
      {id: '824', value: 'Huyện Gò Công Đông'},
      {id: '825', value: 'Huyện Tân Phú Đông'},
    ],
  },
  {
    id: '83',
    value: 'Tỉnh Bến Tre',
    children: [
      {id: '829', value: 'Thành phố Bến Tre'},
      {id: '831', value: 'Huyện Châu Thành'},
      {id: '832', value: 'Huyện Chợ Lách'},
      {id: '833', value: 'Huyện Mỏ Cày Nam'},
      {id: '834', value: 'Huyện Giồng Trôm'},
      {id: '835', value: 'Huyện Bình Đại'},
      {id: '836', value: 'Huyện Ba Tri'},
      {id: '837', value: 'Huyện Thạnh Phú'},
      {id: '838', value: 'Huyện Mỏ Cày Bắc'},
    ],
  },
  {
    id: '84',
    value: 'Tỉnh Trà Vinh',
    children: [
      {id: '842', value: 'Thành phố Trà Vinh'},
      {id: '844', value: 'Huyện Càng Long'},
      {id: '845', value: 'Huyện Cầu Kè'},
      {id: '846', value: 'Huyện Tiểu Cần'},
      {id: '847', value: 'Huyện Châu Thành'},
      {id: '848', value: 'Huyện Cầu Ngang'},
      {id: '849', value: 'Huyện Trà Cú'},
      {id: '850', value: 'Huyện Duyên Hải'},
      {id: '851', value: 'Thị xã Duyên Hải'},
    ],
  },
  {
    id: '86',
    value: 'Tỉnh Vĩnh Long',
    children: [
      {id: '855', value: 'Thành phố Vĩnh Long'},
      {id: '857', value: 'Huyện Long Hồ'},
      {id: '858', value: 'Huyện Mang Thít'},
      {id: '859', value: 'Huyện  Vũng Liêm'},
      {id: '860', value: 'Huyện Tam Bình'},
      {id: '861', value: 'Thị xã Bình Minh'},
      {id: '862', value: 'Huyện Trà Ôn'},
      {id: '863', value: 'Huyện Bình Tân'},
    ],
  },
  {
    id: '87',
    value: 'Tỉnh Đồng Tháp',
    children: [
      {id: '866', value: 'Thành phố Cao Lãnh'},
      {id: '867', value: 'Thành phố Sa Đéc'},
      {id: '868', value: 'Thành phố Hồng Ngự'},
      {id: '869', value: 'Huyện Tân Hồng'},
      {id: '870', value: 'Huyện Hồng Ngự'},
      {id: '871', value: 'Huyện Tam Nông'},
      {id: '872', value: 'Huyện Tháp Mười'},
      {id: '873', value: 'Huyện Cao Lãnh'},
      {id: '874', value: 'Huyện Thanh Bình'},
      {id: '875', value: 'Huyện Lấp Vò'},
      {id: '876', value: 'Huyện Lai Vung'},
      {id: '877', value: 'Huyện Châu Thành'},
    ],
  },
  {
    id: '89',
    value: 'Tỉnh An Giang',
    children: [
      {id: '883', value: 'Thành phố Long Xuyên'},
      {id: '884', value: 'Thành phố Châu Đốc'},
      {id: '886', value: 'Huyện An Phú'},
      {id: '887', value: 'Thị xã Tân Châu'},
      {id: '888', value: 'Huyện Phú Tân'},
      {id: '889', value: 'Huyện Châu Phú'},
      {id: '890', value: 'Huyện Tịnh Biên'},
      {id: '891', value: 'Huyện Tri Tôn'},
      {id: '892', value: 'Huyện Châu Thành'},
      {id: '893', value: 'Huyện Chợ Mới'},
      {id: '894', value: 'Huyện Thoại Sơn'},
    ],
  },
  {
    id: '91',
    value: 'Tỉnh Kiên Giang',
    children: [
      {id: '899', value: 'Thành phố Rạch Giá'},
      {id: '900', value: 'Thành phố Hà Tiên'},
      {id: '902', value: 'Huyện Kiên Lương'},
      {id: '903', value: 'Huyện Hòn Đất'},
      {id: '904', value: 'Huyện Tân Hiệp'},
      {id: '905', value: 'Huyện Châu Thành'},
      {id: '906', value: 'Huyện Giồng Riềng'},
      {id: '907', value: 'Huyện Gò Quao'},
      {id: '908', value: 'Huyện An Biên'},
      {id: '909', value: 'Huyện An Minh'},
      {id: '910', value: 'Huyện Vĩnh Thuận'},
      {id: '911', value: 'Thành phố Phú Quốc'},
      {id: '912', value: 'Huyện Kiên Hải'},
      {id: '913', value: 'Huyện U Minh Thượng'},
      {id: '914', value: 'Huyện Giang Thành'},
    ],
  },
  {
    id: '92',
    value: 'Thành phố Cần Thơ',
    children: [
      {id: '916', value: 'Quận Ninh Kiều'},
      {id: '917', value: 'Quận Ô Môn'},
      {id: '918', value: 'Quận Bình Thuỷ'},
      {id: '919', value: 'Quận Cái Răng'},
      {id: '923', value: 'Quận Thốt Nốt'},
      {id: '924', value: 'Huyện Vĩnh Thạnh'},
      {id: '925', value: 'Huyện Cờ Đỏ'},
      {id: '926', value: 'Huyện Phong Điền'},
      {id: '927', value: 'Huyện Thới Lai'},
    ],
  },
  {
    id: '93',
    value: 'Tỉnh Hậu Giang',
    children: [
      {id: '930', value: 'Thành phố Vị Thanh'},
      {id: '931', value: 'Thành phố Ngã Bảy'},
      {id: '932', value: 'Huyện Châu Thành A'},
      {id: '933', value: 'Huyện Châu Thành'},
      {id: '934', value: 'Huyện Phụng Hiệp'},
      {id: '935', value: 'Huyện Vị Thuỷ'},
      {id: '936', value: 'Huyện Long Mỹ'},
      {id: '937', value: 'Thị xã Long Mỹ'},
    ],
  },
  {
    id: '94',
    value: 'Tỉnh Sóc Trăng',
    children: [
      {id: '941', value: 'Thành phố Sóc Trăng'},
      {id: '942', value: 'Huyện Châu Thành'},
      {id: '943', value: 'Huyện Kế Sách'},
      {id: '944', value: 'Huyện Mỹ Tú'},
      {id: '945', value: 'Huyện Cù Lao Dung'},
      {id: '946', value: 'Huyện Long Phú'},
      {id: '947', value: 'Huyện Mỹ Xuyên'},
      {id: '948', value: 'Thị xã Ngã Năm'},
      {id: '949', value: 'Huyện Thạnh Trị'},
      {id: '950', value: 'Thị xã Vĩnh Châu'},
      {id: '951', value: 'Huyện Trần Đề'},
    ],
  },
  {
    id: '95',
    value: 'Tỉnh Bạc Liêu',
    children: [
      {id: '954', value: 'Thành phố Bạc Liêu'},
      {id: '956', value: 'Huyện Hồng Dân'},
      {id: '957', value: 'Huyện Phước Long'},
      {id: '958', value: 'Huyện Vĩnh Lợi'},
      {id: '959', value: 'Thị xã Giá Rai'},
      {id: '960', value: 'Huyện Đông Hải'},
      {id: '961', value: 'Huyện Hoà Bình'},
    ],
  },
  {
    id: '96',
    value: 'Tỉnh Cà Mau',
    children: [
      {id: '964', value: 'Thành phố Cà Mau'},
      {id: '966', value: 'Huyện U Minh'},
      {id: '967', value: 'Huyện Thới Bình'},
      {id: '968', value: 'Huyện Trần Văn Thời'},
      {id: '969', value: 'Huyện Cái Nước'},
      {id: '970', value: 'Huyện Đầm Dơi'},
      {id: '971', value: 'Huyện Năm Căn'},
      {id: '972', value: 'Huyện Phú Tân'},
      {id: '973', value: 'Huyện Ngọc Hiển'},
    ],
  },
];

export {PLACES};
